services:
  glue:
    container_name: glue-devtools
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - USER_ID=${USER_ID:-}
    volumes:
      - ~/.aws:/home/glue_user/.aws
      - ..:/home/glue_user/workspace
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - DISABLE_SSL=true
      - AWS_PROFILE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    env_file:
      - path: .env
        required: false
    ports:
      - "4040:4040"
      - "18080:18080"
      - "8998:8998"
      - "8888:8888"
    command: /home/glue_user/workspace/docker/jupyter-start.sh
