name: Checks

on:
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  python:
    name: Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5.1.1
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install Python Dependencies
        run: |
          poetry check --lock
          poetry install --no-root
      - name: Lint Python code using ruff
        run: |
          poetry run ruff format . --check
          poetry run ruff check .
      - name: Check type annotations using mypy
        run: poetry run mypy
      - name: Check imports using import-linter
        run: poetry run lint-imports
      - name: Check if requirements.txt is in sync with poetry.lock
        run: poetry export --with=dev --output docker/requirements.txt && git diff --exit-code
      - name: Set up NodeJS
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"
      - name: Synthesize CDK deployment package
        run: npx aws-cdk synth --strict
  tests:
    name: Run tests in Glue container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Pull official glue image
        run: docker pull amazon/aws-glue-libs:glue_libs_4.0.0_image_01
      - name: Build container
        run: USER_ID=$(id -u) docker compose --file docker/docker-compose.yml build glue
      - name: Run tests in container
        run: USER_ID=$(id -u) docker compose --file docker/docker-compose.yml run glue -c pytest
  shell:
    name: Shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Check shell scripts using shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
  dockerfile:
    name: Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Validate Dockerfile using hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/Dockerfile
  makefile:
    name: Makefile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Check Makefile using checkmake
        uses: Uno-Takashi/checkmake-action@v2
