name: Checks

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  python:
    name: Python Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Check shell scripts
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: '.'

      - name: Setup Virtualenv Cache
        uses: actions/cache@v4.0.0
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Set up Python 3.10
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.10.13"

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8

      - name: Install Python Dependencies
        run: poetry install --no-root

      - name: Check poetry config
        run: poetry check

      - name: Lint Python code
        run: |
          poetry run ruff format . --check
          poetry run ruff check .

      - name: Check type annotations
        run: poetry run mypy